
services:
  docker-backup:
    build: .
    container_name: docker-backup
    restart: unless-stopped
    
    # Environment configuration
    env_file:
      - .env
    
    environment:
      # Backblaze B2 S3-compatible endpoint (override AWS default)
      - AWS_ENDPOINT_URL=https://s3.${AWS_REGION:-us-west-004}.backblazeb2.com
      # Set timezone for cron jobs
      - TZ=${TZ:-UTC}
    
    volumes:
      # Docker socket access (required for container inspection)
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
      # Docker volumes directory (adjust path as needed)
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      
      # Additional volume paths (uncomment and modify as needed)
      # - /data/docker-volumes:/data/docker-volumes:ro
      # - /opt/docker/volumes:/opt/docker/volumes:ro
      
      # Backup state persistence
      - ./backup-data:/app/backup-data
      
      # Logs persistence
      - ./logs:/app/logs
      
      # Configuration persistence
      - ./.env:/app/.env:ro
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 30s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Labels for management
    labels:
      - "com.docker.compose.project=docker-backup"
      - "service.description=Automated Docker volume backup with Telegram notifications"
      - "service.schedule=daily-2am"

  # Optional: Watchtower for auto-updates
  watchtower:
    image: containrrr/watchtower
    container_name: docker-backup-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * *  # Check for updates at 4 AM
      - WATCHTOWER_MONITOR_ONLY=true     # Set to false to enable auto-updates
    labels:
      - "com.docker.compose.project=docker-backup"